# Generated by Django 4.2.4 on 2024-12-17 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrecioHistoricoVehiculos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("modelo", models.CharField(max_length=120)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
